#!/bin.sh

#IMPORTANT THINGS MUST START FIRST
nm-applet& #network manager
while true; do
    date=`date +"%A %B %d %R"`;
    volume=`getvol`
   xsetroot -name "Vol: $volume - $date";
   sleep 1m    # Update every minute

done &
redshift -l -33.867139:151.207114& #redshift
numlockx on&

#LESS IMPORTANT THINGS CAN START LATER, otherwise login is very slow
sleep 1m;
unclutter -idle 1& #hides mouse pointer after 1 second of inactivity
/usr/bin/gnome-keyring-daemon --start --components=secrets & #key managment
/usr/bin/gnome-keyring-daemon --start --components=ssh & #key managment
/usr/bin/gnome-keyring-daemon --start --components=pkcs11 & #key managment
